version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: app
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/home/node/app
    depends_on:
      - database

  database:
    build: .docker/postgres
    container_name: database
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/database/development:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=cursonestjsprisma
      - POSTGRES_DB=cursonestjsprisma
